name: Build and Test
on:
  push:
    branches:
      - dev
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          ref: dev

      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: https://registry.npmjs.org/

      - name: npm install, build, test
        run: |
          npm install -g yarn
          yarn
          yarn run tsc
          yarn run test
