name: Build and Deploy Doc
on:
  push:
    branches:
      - dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: dev

      - name: Duild
        run: |
          npm install -g yarn
          cd docs
          yarn
          yarn run docs:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        env:
          deploy_key: ${{secrets.ACTIONS_DEPLOY_KEY}}
          publish_branch: gh-pages
          publish_dir: docs/.vuepress/dist
